/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillGapRouteImport } from './routes/_authenticated/skill-gap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'
import { Route as AuthenticatedInterviewPrepRouteImport } from './routes/_authenticated/interview-prep'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedAptitudeRouteImport } from './routes/_authenticated/aptitude'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillGapRoute = AuthenticatedSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewPrepRoute =
  AuthenticatedInterviewPrepRouteImport.update({
    id: '/interview-prep',
    path: '/interview-prep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAptitudeRoute = AuthenticatedAptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aptitude': typeof AuthenticatedAptitudeRoute
  '/career': typeof AuthenticatedCareerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aptitude': typeof AuthenticatedAptitudeRoute
  '/career': typeof AuthenticatedCareerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/aptitude': typeof AuthenticatedAptitudeRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interview-prep': typeof AuthenticatedInterviewPrepRoute
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/aptitude'
    | '/career'
    | '/dashboard'
    | '/interview-prep'
    | '/mock-interview'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/aptitude'
    | '/career'
    | '/dashboard'
    | '/interview-prep'
    | '/mock-interview'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/aptitude'
    | '/_authenticated/career'
    | '/_authenticated/dashboard'
    | '/_authenticated/interview-prep'
    | '/_authenticated/mock-interview'
    | '/_authenticated/profile'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skill-gap': {
      id: '/_authenticated/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AuthenticatedSkillGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview-prep': {
      id: '/_authenticated/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof AuthenticatedInterviewPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aptitude': {
      id: '/_authenticated/aptitude'
      path: '/aptitude'
      fullPath: '/aptitude'
      preLoaderRoute: typeof AuthenticatedAptitudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAptitudeRoute: typeof AuthenticatedAptitudeRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewPrepRoute: typeof AuthenticatedInterviewPrepRoute
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillGapRoute: typeof AuthenticatedSkillGapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAptitudeRoute: AuthenticatedAptitudeRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewPrepRoute: AuthenticatedInterviewPrepRoute,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillGapRoute: AuthenticatedSkillGapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
